## read files
```{r}
filename = "test.csv"
test_data <- read.csv(filename,header=T)
filename = "train.csv"
train_data <- read.csv(filename,header=T)

```

## Boxplots
```{r}
boxplot(Danceability~genre,data=train_data, xlab="genre", ylab="Danceability")
boxplot(Energy~genre,data=train_data, xlab="genre", ylab="Energy")
boxplot(Key~genre,data=train_data, xlab="genre", ylab="Key")
boxplot(Loudness~genre,data=train_data, xlab="genre", ylab="Loudness")
boxplot(Mode~genre,data=train_data, xlab="genre", ylab="Mode")
boxplot(Speechness~genre,data=train_data, xlab="genre", ylab="Speechness")
boxplot(Acousticness~genre,data=train_data, xlab="genre", ylab="Acousticness")
boxplot(Instrumentalness~genre,data=train_data, xlab="genre", ylab="Instrumentalness")
boxplot(Liveness~genre,data=train_data, xlab="genre", ylab="Liveness")
boxplot(Valence~genre,data=train_data, xlab="genre", ylab="Valence")
boxplot(Tempo~genre,data=train_data, xlab="genre", ylab="Tempo")
boxplot(Duration_ms~genre,data=train_data, xlab="genre", ylab="Duration_ms")

```


## KNN min MSE = 0.4651779 at K= 40
```{r}
library(class)
library(kknn)
#54, 1:10, 13 -- 0.466
#42 1,2,4,6,7,8,9,10,13 -- 0.466

        
kk = c(40,41,42,43) #20,30,40,50,60,70,80,90
col = c(1:2,4,6:10,13)

MSE = NULL
scale_train_data <- scale(train_data[,col]) 
scale_test_data <- scale(test_data[,col])
set.seed(1)
for(j in kk){
  nearest <- knn(train = scale_train_data, test = scale_test_data, cl=train_data$genre, k=j)
  aux =  mean(nearest != test_data$genre)
  MSE = c(MSE,aux)
    
}
plot(kk,MSE,type="b",xlab="k",col="blue",ylab="MSE",lwd=2,cex.lab=1.2)
MSE[which.min(MSE)]
```
## graphs (will not be used)
```{r}
nearest <- knn(train = scale_train_data, test = scale_test_data, cl=train_data$genre, k=40)
result <-data.frame(test_data$genre,nearest)
result[result$nearest == result$test_data.genre,"Equal"] <- 1
aux =  1 - nrow(subset(result, result$Equal == 1)) / nrow(result)
par(mfrow=c(1,1))
plot(scale_train_data, col=train_data$genre, cex=.8,pch=1)

  for(i in 1:10){
    points(scale_test_data[i,1],scale_test_data[i,2], pch=18, col="orange", cex=2)
    points(scale_test_data[i,1],scale_test_data[i,2], pch=18, col=nearest[i], cex=2)
}

```


## Bagging min MSE = 0.4062263 with 24 trees
```{r}
library(randomForest)
set.seed (1)

MSE = NULL
ntree = c(10:40)
for (i in ntree){
  bag.music =randomForest(genre ~ Danceability + Energy + Key + Loudness + Mode           + Speechness + Acousticness + Instrumentalness + Liveness + Valence + Tempo + Duration_ms, data=train_data ,
  mtry=12, ntree = i) 
  
  yhat.bag = predict(bag.music,newdata = test_data)
  aux =  mean( yhat.bag != test_data$genre)
  MSE = c(MSE,aux)
}
plot(ntree, MSE,type="b",xlab="ntree",col="blue",ylab="MSE",lwd=2,cex.lab=1.2)
MSE[which.min(MSE)]
```


